<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New Martian databaseDatabase_1New solar_05144d</name>
   <tag></tag>
   <elementGuidId>e2257fea-01ba-43eb-85a7-e9497c90174c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_ids']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui fluid search selection multiple dropdown</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tagshtml</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tags</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Martian databaseDatabase_1New solar databasePL-5221New astral databaseNew astral databaseNew interplanetary databaseNew awesome databaseNew stellar databaseDatabase_New planetary databaseDatabase_1New meteoric databaseNew lunar databasedatabase))API_databasedatabaseImport_dbStellar astral databasemillion_databaseNew stellar databaseDatabase_51ImportNew powerful databasePushokNew intergalactic database&amp;gt;?&amp;gt;?&amp;gt;:123databases123databasesNew awesome databaseNew interplanetary databaseNew powerful databaseNew Martian databaseNew celestial databaseNew_DNew_CNew_BNew_ANew awesome database importD22D11DB_Stat_Sdatabase__22database__11New22222222New111111111Dev_database2Dev_database1database_Bdatabase_Abase2base1Db2db1database2database1Rel_databaseap123push safariPushBBBAAAPostgre databasePPPPNew Martian databaseNew planetary database333TestData1DataNew cosmic database100 databaseNew galactic databaseNew awesome databasedb124 - New Martian database123 - Database_1122 - New solar database121 - PL-5221119 - New astral database118 - New astral database117 - New interplanetary database116 - New awesome database115 - New stellar database109 - Database_108 - New planetary database107 - Database_1106 - New meteoric database105 - New lunar database104 - database))102 - API_database101 - database100 - Import_db86 - Stellar 85 - astral database84 - million_database83 - New stellar database74 - Database_5173 - Import72 - New powerful database71 - Pushok70 - New intergalactic database69 - >?>?>:68 - 123databases67 - 123databases66 - New awesome database65 - New interplanetary database64 - New powerful database63 - New Martian database62 - New celestial database61 - New_D60 - New_C59 - New_B58 - New_A57 - New awesome database import56 - D2255 - D1154 - DB_Stat_S53 - database__2252 - database__1151 - New2222222250 - New11111111149 - Dev_database248 - Dev_database147 - database_B46 - database_A45 - base244 - base143 - Db242 - db141 - database240 - database139 - Rel_database38 - ap37 - 12336 - push safari35 - Push34 - BBB33 - AAA32 - Postgre database31 - PPPP30 - New Martian database29 - New planetary database28 - 33327 - Test22 - Data121 - Data6 - New cosmic database4 - 100 database3 - New galactic database2 - New awesome database1 - db</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_ids&quot;)/div[@class=&quot;ui fluid search selection multiple dropdown&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_ids']/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Базы данных:'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Не определена'])[3]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URL веб-сайта, формы или приложения:'])[1]/preceding::div[80]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Трекинг домен по умолчанию:'])[1]/preceding::div[81]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div</value>
   </webElementXpaths>
</WebElementEntity>
